Final_project/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views

from django.contrib import admin
from blog import views
from django.conf import settings
from django.conf.urls.static import static
from blog.views import (
    AboutView,
    PostSearch,
    ContactView,
    ContactCompleteView,
    CategoryUpdateView,
    CreateCategoryView,
    DeletePhoto,
    DeleteUser,
    DeleteCategoryView,
    AddPhotoView,
    CreatePost,
    UpdatePost,
    DeletePost,
    UpdateProfile,
    UpdateAvatar,
    ProfileView,
    SignupView,
    SignupViewComplete,
    PostView,
    MainView,
    AuthorView,
    CategoriesView,
    CategoryView,
    CommentUpdate,
    CommentsView,
    DeleteComment,
    CreatePostComplete,
)
from django.views.decorators.http import require_POST

urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    # path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path("", MainView.as_view(), name="main"),
    path("post/<slug:post_slug>/", PostView.as_view(), name="post_details"),
    path("create_post/", CreatePost.as_view(), name="create-post"),
    path("post/edit/<slug:slug>/", UpdatePost.as_view(), name="update-post"),
    path("post/delete/<slug:slug>/", DeletePost.as_view(), name="delete-post"),
    path("post/done/", CreatePostComplete.as_view(), name='create-post-complete'),
    path("post/search", PostSearch.as_view(), name="post-search"),
    path("author/<str:post_author>/", AuthorView.as_view(), name="author_posts"),
    path("categories/", CategoriesView.as_view(), name="categories"),
    path("category/<int:category_id>", CategoryView.as_view(), name="category_details"),
    path("category/delete/<int:pk>/", DeleteCategoryView.as_view(), name="delete-category"),
    path("category/edit/<int:pk>/", CategoryUpdateView.as_view(), name="update-category"),
    path("create_category/", CreateCategoryView.as_view(), name="create-category"),
    path("comments/", CommentsView.as_view(), name="comments"),
    path("comment/edit/<int:pk>/", CommentUpdate.as_view(), name="update_comment"),
    path("comments/delete/<int:pk>/", DeleteComment.as_view(), name="delete_comment"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("signup/done/", SignupViewComplete.as_view(), name='signup-complete'),
    path("update_avatar/<int:pk>/", UpdateAvatar.as_view(), name="update-avatar"),
    path("update_profile/<int:pk>/", UpdateProfile.as_view(), name="update-profile"),
    path("add_photo/", AddPhotoView.as_view(), name="add-photo"),
    path("delete_photo/<int:pk>", DeletePhoto.as_view(), name="delete-photo"),
    path("about/", AboutView.as_view(), name="about"),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/done/', ContactCompleteView.as_view(), name='contact-success'),

    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(next_page="main"),
        name="logout",
    ),
    path("accounts/delete/<int:pk>", DeleteUser.as_view(), name='delete-user'),
    path("", include("social_django.urls", namespace="social")),
    path("accounts/profile/", ProfileView.as_view(), name="profile"),
    path("accounts/", include("django.contrib.auth.urls")),

    re_path(
        r"^password_reset/$",
        auth_views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    re_path(
        r"^password_reset/done/$",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    re_path(
        r"^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    re_path(
        r"^reset/done/$",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.


class Category(models.Model):
    """
    All posts are assigned to one or multiple categories - like tags
    """
    name = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return self.name


class Photo(models.Model):
    description = models.CharField(max_length=100)
    uploaded_by = models.ForeignKey(
        User,
        verbose_name=("Photo Uploader"),
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    image = models.ImageField(
        upload_to="photos", blank=True, verbose_name="Photo to upload"
    )

    def __str__(self):
        return f"Photo: {str(self.id)} Title: {self.description}"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # avatar = models.ImageField(upload_to="profile/", blank=True)
    avatar = models.ImageField(blank=True)

    email_confirmed = models.BooleanField(default=False)
    reset_password = models.BooleanField(default=False)
    def __str__(self):  
        return f'{self.user}s\'s profile'

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
post_save.connect(create_user_profile, sender=User)

STATUS = ((0, "Published"), (1, "Draft"))

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=150, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_posts"
    )
    edited_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField(verbose_name="Post content")
    status = models.IntegerField(choices=STATUS, default=1)
    photos = models.ManyToManyField(Photo, related_name="posts", blank=True)
    categories = models.ManyToManyField(Category, related_name="category_posts", blank=True)

    class Meta:
        ordering = ["-created_on"]

    def pub_date(self):
        return self.created_on.strftime("%b %e, %Y")

    def summary(self):
        return self.content[:100]

    def __str__(self):
        return self.title


def get_deleted_user_instance():
    return User.objects.get(username="deleted")


class Comment(models.Model):
    rating = models.IntegerField(default=0, null=True, blank=True)
    content = models.TextField()
    author = models.ForeignKey(
        User,
        on_delete=models.SET(get_deleted_user_instance),
        related_name="author_comments",
    )
    source_post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="post_comments"
    )
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_on"]

    def summary(self):
        return self.content[:30]

    def __str__(self):
        return f"{self.content[:10]} by {self.author.username}"

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, FormView, CreateView, ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin, UpdateView, DeleteView
from django.contrib.auth.mixins import (
    PermissionRequiredMixin,
    LoginRequiredMixin,
    UserPassesTestMixin,
)
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Count, Q
from django.utils.text import slugify
from django.core.mail import send_mail, BadHeaderError
from django.core.paginator import Paginator

from .models import Post, Comment, Category, UserProfile, Photo
from .forms import (
    PostSearchForm,
    CommentForm,
    UserSignUpForm,
    AddPhotoForm,
    UpdatePostForm,
    CreatePostForm,
    UpdateUserForm,
    ContactForm,
    CreateCategoryForm,
)
from django.views import View
from django.urls import reverse_lazy


class MainView(ListView):
    template_name = "main.html"
    paginate_by = 5
    queryset = Post.objects.filter(status=0)
    context_object_name = "posts"


class CreatePost(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("login")

    model = Post
    form_class = CreatePostForm
    success_url = reverse_lazy("main")

    def post(self, request, *args, **kwargs):
        form = CreatePostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.slug = slugify(post.title, allow_unicode=False)
            post.author = request.user
            post.save()
            return redirect('main')
        else:
            return render(request, 'blog/post_form.html', {'form': form})            


class UpdatePost(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    login_url = reverse_lazy("login")

    model = Post
    form_class = UpdatePostForm
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("main")

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class DeletePost(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    login_url = reverse_lazy("login")

    model = Post

    def get_success_url(self):
        return self.request.GET.get("next", reverse_lazy("main"))

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class PostView(FormMixin, DetailView):
    template_name = "post_details.html"
    slug_url_kwarg = "post_slug"
    slug_field = "slug"
    model = Post
    form_class = CommentForm

    def get_success_url(self):
        return reverse_lazy("post_details", kwargs={"post_slug": self.object.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = Comment.objects.filter(source_post__pk=context["post"].pk)
        current_post = Post.objects.get(slug=self.object.slug)
        attached_photos = current_post.photos.all()

        context["comments"] = comments
        context["form"] = CommentForm(
            initial={"source_post": self.object, "author": self.request.user}
        )
        context["attached_photos"] = attached_photos
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.source_post = self.object
            comment.save()

            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(PostView, self).form_valid(form)


class AuthorView(TemplateView):
    template_name = "author_posts.html"

    def get_context_data(self, post_author):
        posts = Post.objects.filter(author__username=str(post_author))
        ctx = {"posts": posts, "author": post_author}
        return ctx


class CategoriesView(TemplateView):
    template_name = "categories.html"

    def get_context_data(self):
        categories_by_post_no = (
            Category.objects.all()
            .annotate(post_count=Count("category_posts"))
            .order_by("post_count")
            .reverse()
            .values("id", "name", "post_count")
        )
        ctx = {"categories_by_post_no": categories_by_post_no}
        return ctx


class CommentsView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy("login")
    template_name = "comments.html"

    def get_context_data(self, **kwargs):
        comments_by_logged_user = Comment.objects.filter(author=self.request.user)
        ctx = {"comments_by_logged_user": comments_by_logged_user}
        return ctx


class CategoryView(TemplateView):
    template_name = "category.html"

    def get_context_data(self, category_id):
        category_id = int(str(category_id))
        cat = get_object_or_404(Category, id=category_id)
        posts = Post.objects.filter(categories__id=category_id)
        return {"cat": cat, "posts": posts}


class CommentUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    fields = ["content"]
    template_name_suffix = "_update_form"
    success_url = "main"

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class DeleteComment(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    login_url = reverse_lazy("login")
    model = Comment

    def get_success_url(self):
        return self.request.GET.get("next", reverse_lazy("main"))

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class SignupView(CreateView):
    form_class = UserSignUpForm
    success_url = reverse_lazy("signup-complete")
    template_name = "signup.html"

class SignupViewComplete(TemplateView):
    template_name = "signup_complete.html"
    success_url = reverse_lazy("main")

class CreatePostComplete(TemplateView):
    template_name = "post_complete.html"
    success_url = reverse_lazy("main")

class ProfileView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy("login")
    template_name = "profile.html"

    def get_context_data(self):
        u = self.request.user  # .get_profile()
        users = User.objects.all()
        posts = Post.objects.filter(author__id=u.pk)
        comments = Comment.objects.filter(author__pk=u.pk)
        photos = Photo.objects.filter(uploaded_by__id=u.pk)
        return {"posts": posts, "comments": comments, "photos": photos, "users": users}


class UpdateAvatar(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    login_url = reverse_lazy("login")
    model = UserProfile
    fields = ("avatar",)
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("main")

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user


class UpdateProfile(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    login_url = reverse_lazy("login")
    form_class = UpdateUserForm
    model = User
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("main")

    def test_func(self):
        obj = self.get_object()
        return obj.pk == self.request.user.pk


class AddPhotoView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("login")

    model = Photo
    form_class = AddPhotoForm
    template_name = "add_photo.html"
    success_url = reverse_lazy("profile")

    def post(self, request, *args, **kwargs):
        # self.object = self.get_object()
        form = AddPhotoForm(request.POST, request.FILES)
        # form = self.get_form()
        if form.is_valid():
            photo = form.save(commit=False)
            photo.uploaded_by = request.user
            photo.save()
            return redirect('main')
        else:
            return render(request, 'blog/add_photo.html', {'form': form})   


class DeletePhoto(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy("login")

    model = Photo

    def get_success_url(self):
        return self.request.GET.get("next", reverse_lazy("main"))


class PostSearch(TemplateView):
    template_name = "post_search.html"

    def get_context_data(self, **kwargs):
        if self.request.GET:
            form = PostSearchForm(self.request.GET)
            if form.is_valid():
                posts = Post.objects.filter(
                    Q(title__icontains=form.cleaned_data["content"])
                    | Q(content__icontains=form.cleaned_data["content"])
                )

            else:
                posts = []
        else:
            form = PostSearchForm()
            posts = None
        ctx = {"form": form, "posts": posts}
        return ctx


class AboutView(TemplateView):
    template_name = "about.html"


class DeleteUser(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """ Delete user if owner or staff member logged in"""

    login_url = reverse_lazy("main")
    model = User

    def get_success_url(self):
        return self.request.GET.get("next", reverse_lazy("main"))

    def test_func(self):
        obj = self.get_object()
        if obj == self.request.user or self.request.user.is_staff:
            return True
        else:
            return False


class ContactView(FormView):
    form_class = ContactForm 
    template_name = "contact.html"
    success_url = reverse_lazy("contact-success")

    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['borkowski.bartosz@gmail.com'])

templates/blog/category_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-md-8">
      
<div class="col-md-8">
<h3 class="my-4"><small></small></h3>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
   <h3 class="my-4">Are you sure?</h3><input type="submit" class="btn btn-danger" value="Delete Comment">
</form>
</div> 
      </div>

{% endblock %}

templates/blog/category_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
  <div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">
      <div class="card my-4">
        <h5 class="card-header">Add a category</h5>
        <div class="card-body">
          <form method='POST'>
            {% csrf_token %}
            {{form.as_p}}
        </div>
        <button type="submit" class="btn btn-success">Add</button>
      </div>
        </form>
    </div>
    </form>

    {% endblock %}

templates/blog/category_update_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <div class="container">
    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">
       <div class="card my-4">
          <h5 class="card-header">Update category:</h5>
          <div class="card-body">
            <form method='POST'>
              {% csrf_token %}
              <div class="form-group">

              <input class="form-control" name="content" required="" id="id_name" value={{object.name}}></input>
              </div>
              <button type="submit" class="btn btn-primary" >Update</button>
            </form>
          </div>
        </div>
        </form>
      </div>

{% endblock %}


 

templates/blog/comment_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-md-8">
      
<div class="col-md-8">
<h3 class="my-4"><small></small></h3>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
   <h3 class="my-4">Are you sure?</h3><input type="submit" class="btn btn-danger" value="Delete Comment">
</form>
</div> 
      </div>

{% endblock %}

templates/blog/comment_update_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <div class="container">
    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">
       <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form method='POST'>
              {% csrf_token %}
              <div class="form-group">
              <textarea class="form-control" name="content" cols="40" rows="10" required="" id="id_content">{{object.content}}</textarea>
              </div>
              <button type="submit" class="btn btn-primary" >Update</button>
            </form>
          </div>
        </div>
        </form>
      </div>

{% endblock %}


 

templates/blog/photo_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-md-8">
      
<div class="col-md-8">
<h3 class="my-4"><small></small></h3>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
   <h3 class="my-4">Are you sure?</h3><input type="submit" class="btn btn-danger" value="Delete Photo">
</form>
</div> 
</div>

{% endblock %}

templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<!-- Page Content -->
<div class="container">
  <div class="row">
    <div class="col-md-8">

      <div class="col-md-8">
        <h3 class="my-4"><small></small></h3>
        <form action="" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <h3 class="my-4">Are you sure?</h3><input type="submit" class="btn btn-danger" value="Delete Post">
        </form>
      </div>
    </div>

    {% endblock %}

templates/blog/post_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
  <div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">
      <div class="card my-4">
        <h5 class="card-header">Create Post</h5>
        <div class="card-body">
          <h5 class="my-4"><a class="btn btn-success btn-sm" href="{% url 'add-photo'%}?next={{request.path}}" role="button"
              alt="Add a photo">Add new photo</a></h5>
          <form method='POST'>
            {% csrf_token %}
            {{form.as_p}}
        </div>
        <button type="submit" class="btn btn-success">Create</button>
        </form>
      </div>
    </div>
    </form>

    {% endblock %}

templates/blog/post_update_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <div class="container">
    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">
       <div class="card my-4">
          <h5 class="card-header">Update Post</h5>
          <div class="card-body">
            <form method='POST'>
              {% csrf_token %}
              {{form.as_p}}
              <button type="submit" class="btn btn-primary" >Update</button>
              </div>
            </form>
          </div>
        </div>
        </form>

{% endblock %}


 

templates/blog/userprofile_update_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <div class="container">
    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">
       <div class="card my-4">
          <h5 class="card-header">Update Avatar</h5>
          <div class="card-body text-center">
            {% if user.userprofile.avatar %}
            <img class="rounded border" style="width:200px" src="{{user.userprofile.avatar.url}}">
            {% elif user.first_name and user.last_name %}
            <img class="rounded" src="https://avatars.dicebear.com/api/initials/{{user.first_name.0}}_{{user.last_name.0}}.svg" style="width:200px" alt="">
            {% else %}
            <img class="rounded" src="https://avatars.dicebear.com/api/initials/{{user.username.0}}.svg" style="width:200px" alt="">
            {% endif %}
            <hr>
            <form method='POST' enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group">
                {{form.as_p}}
              </div>
              <button type="submit" class="btn btn-primary" >Update</button>
            </form>
          </div>
        </div>
        </form>
      </div>

{% endblock %}


 